name: Jest Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        options: --health-cmd="exit 0" # Disable health check to avoid flakiness
        ports:
          - 27017:27017
        # timeout: 300s # Increase timeout

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
        # retry: 3 # Add retry logic
