name: Jest Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        options: --health-cmd="exit 0" # Disable health check to avoid flakiness
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --force

      - name: approve builds
        run: pnpm approve-builds <<< a

      - name: pwd
        run: pwd

      - name: ls
        run: ls node_modules

      - name: ls
        run: ls node_modules/.pnpm/

      - name: Run tests
        run: pnpm test

      - name: Test build
        run: pnpm build
